### ISSUE TITLE
Please add the homepage and GitHub URL to package.json

### ISSUE THREAD

**Issue by niftylettuce** [renanvaz/trim-image#1]
It is not obvious where the package is hosted, because you published to npm without required fields in package.json.

To fix this, you can run `npm install -g fixpack` and then run `fixpack` in the root of this repo.

It will then tell you what fields are missing and you can add them.

Once done bump the version in package.json and publish a new version to npm.

**Comment by renanvaz** [comment]
Hi @niftylettuce, thanks for the feedback. 

I have published a new version of `package.json` with some fields. 
https://www.npmjs.com/package/trim-image

Do you think this needs more fields?

**Comment by niftylettuce** [comment]
Perfect @renanvaz thank you so much for doing this 👏 👍 😄
